image: publysher/hugo

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

production:
  type: deploy
  before_script:
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - hugo
  - aws s3 sync public/ s3://www.worldofnic.org/
  artifacts:
    paths:
    - public
  only:
  - master
