
---
disablePathToLower: true
languageCode: en-us
googleAnalytics: UA-34783744-1
relativeURLs: false
canonifyURLs: false
baseurl: "https://www.worldofnic.org/"
title: "world of nic"
footnotereturnlinkcontents: "↩"
disableRSS: true
disable404: false
disableSitemap: true
theme: "won2017"
params:
  Subtitle: "now lower in saturated fats"
  AuthorName: "Nicolas Doye"
  GitHubUser: "nicdoye"
