# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Stolen From Somewhere"
license = "MIT"
licenselink = "https://github.com/nicdoye/stolen-from-somewhere/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Nicolas Doye"
  homepage = "http://worldofnic.org"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
